### ISSUE TITLE
error: implicitly declaring library function 'snprintf', 'strdup'

### ISSUE THREAD

**Issue by ryandesign** [gphoto/gphoto2#373]
**Describe the bug**

Like gphoto/libgphoto2#552, gphoto2 fails to build on macOS (10.13.6 but should be same on other versions) when implicitly defined functions are not allowed. The first errors are:

```
gp-params.c:166:17: error: implicitly declaring library function 'snprintf' with type 'int (char *, unsigned long, const char *, ...)' [-Werror,-Wimplicit-function-declaration]
                snprintf (buf, sizeof (buf), "%2ih", (int) sec / 3600);
                ^
gp-params.c:166:17: note: include the header <stdio.h> or explicitly provide a declaration for 'snprintf'
gp-params.c:261:14: error: implicitly declaring library function 'strdup' with type 'char *(const char *)' [-Werror,-Wimplicit-function-declaration]
        p->folder = strdup ("/");
                    ^
gp-params.c:261:14: note: include the header <string.h> or explicitly provide a declaration for 'strdup'
2 errors generated.
shell.c:201:3: error: implicitly declaring library function 'snprintf' with type 'int (char *, unsigned long, const char *, ...)' [-Werror,-Wimplicit-function-declaration]
                snprintf (prompt, sizeof (prompt), SHELL_PROMPT, "\0", "\0");
                ^
shell.c:201:3: note: include the header <stdio.h> or explicitly provide a declaration for 'snprintf'
shell.c:283:11: error: implicitly declaring library function 'strdup' with type 'char *(const char *)' [-Werror,-Wimplicit-function-declaration]
                return (strdup (func[x++].command));
                        ^
shell.c:283:11: note: include the header <string.h> or explicitly provide a declaration for 'strdup'
2 errors generated.
```

As in gphoto/libgphoto2#552, adding `-D_DARWIN_C_SOURCE` to CFLAGS works around the issue.

**libgphoto2 and gphoto2 version**
libgphoto2 2.5.26
gphoto2 2.5.26

**To Reproduce**

Compile with the version of clang that comes with Xcode 12 or later, or with earlier clang adding `-Werror=implicit-function-declaration` to CFLAGS.

**Comment by msmeissn** [comment]
i added it in all functions that use strdup there

**Comment by msmeissn** [comment]
i added it in all functions that use strdup there
